- id: doi: 10.1109/ISC2.2018.8656854
  type: paper
  image: https://www.researchgate.net/profile/Feng-Ye-14/publication/331526209/figure/fig1/AS:745086400868355@1554653849980/Overview-of-the-distributed-network-QoE-measurement-framework_W640.jpg
